version: '3'

services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - /home/user/Lab/Lab_Jenkins/volume/jenkins/jenkins_home:/var/jenkins_home

  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "80:8080"
    depends_on:
      - ldap
    volumes:
      - /home/user/Lab/Lab_Jenkins/volume/gerrit/etc:/var/gerrit/etc
      - /home/user/Lab/Lab_Jenkins/volume/gerrit/git:/var/gerrit/git
      - /home/user/Lab/Lab_Jenkins/volume/gerrit/index:/var/gerrit/index
      - /home/user/Lab/Lab_Jenkins/volume/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://localhost
    entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit

  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - /home/user/Lab/Lab_Jenkins/volume/ldap/var:/var/lib/ldap
      - /home/user/Lab/Lab_Jenkins/volume/ldap/etc:/etc/ldap/slapd.d

  ldap-admin:
    image: osixia/phpldapadmin
    ports:
      - "8082:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap

  registry:
    image: registry:2
    ports: 
      - "5000:5000"
