#cloud-config
hostname: first_instance
users:
  - default
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    home: /home/stack
    shell: /bin/bash
    lock_passwd: false
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDXR4acgWnxzTVDlhvlJv1h98Qb>

# only cert auth via ssh (console access can still login)
ssh_pwauth: false
disable_root: false
chpasswd:
  list: |
     ubuntu:ubuntu
  expire: False

# written to /var/log/cloud-init-output.log
final_message: "The system is finally up, after $UPTIME seconds"
